# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datamonitor.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1354, 738)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LayoutDatashow = QtWidgets.QVBoxLayout()
        self.LayoutDatashow.setObjectName("LayoutDatashow")
        self.PB_reloadfile = QtWidgets.QPushButton(self.centralwidget)
        self.PB_reloadfile.setObjectName("PB_reloadfile")
        self.LayoutDatashow.addWidget(self.PB_reloadfile)
        self.dataTable = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTable.sizePolicy().hasHeightForWidth())
        self.dataTable.setSizePolicy(sizePolicy)
        self.dataTable.setTabKeyNavigation(False)
        self.dataTable.setTextElideMode(QtCore.Qt.ElideLeft)
        self.dataTable.setObjectName("dataTable")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dataTable.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dataTable.headerItem().setFont(1, font)
        self.LayoutDatashow.addWidget(self.dataTable)
        self.horizontalLayout.addLayout(self.LayoutDatashow)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 198, 689))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.groupBoxWarning = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBoxWarning.setGeometry(QtCore.QRect(10, 20, 181, 521))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxWarning.setFont(font)
        self.groupBoxWarning.setFlat(False)
        self.groupBoxWarning.setCheckable(False)
        self.groupBoxWarning.setObjectName("groupBoxWarning")
        self.groupBoxCurrentFan1 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan1.setGeometry(QtCore.QRect(10, 30, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan1.setFont(font)
        self.groupBoxCurrentFan1.setObjectName("groupBoxCurrentFan1")
        self.labelStatusFan1 = QtWidgets.QLabel(self.groupBoxCurrentFan1)
        self.labelStatusFan1.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan1.setFont(font)
        self.labelStatusFan1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan1.setText("")
        self.labelStatusFan1.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan1.setScaledContents(True)
        self.labelStatusFan1.setObjectName("labelStatusFan1")
        self.groupBoxCurrentFan2 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan2.setGeometry(QtCore.QRect(10, 90, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan2.setFont(font)
        self.groupBoxCurrentFan2.setObjectName("groupBoxCurrentFan2")
        self.labelStatusFan2 = QtWidgets.QLabel(self.groupBoxCurrentFan2)
        self.labelStatusFan2.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan2.setFont(font)
        self.labelStatusFan2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan2.setText("")
        self.labelStatusFan2.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan2.setScaledContents(True)
        self.labelStatusFan2.setObjectName("labelStatusFan2")
        self.groupBoxCurrentFan3 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan3.setGeometry(QtCore.QRect(10, 150, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan3.setFont(font)
        self.groupBoxCurrentFan3.setObjectName("groupBoxCurrentFan3")
        self.labelStatusFan3 = QtWidgets.QLabel(self.groupBoxCurrentFan3)
        self.labelStatusFan3.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan3.setFont(font)
        self.labelStatusFan3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan3.setText("")
        self.labelStatusFan3.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan3.setScaledContents(True)
        self.labelStatusFan3.setObjectName("labelStatusFan3")
        self.groupBoxCurrentFan4 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan4.setGeometry(QtCore.QRect(10, 210, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan4.setFont(font)
        self.groupBoxCurrentFan4.setObjectName("groupBoxCurrentFan4")
        self.labelStatusFan4 = QtWidgets.QLabel(self.groupBoxCurrentFan4)
        self.labelStatusFan4.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan4.setFont(font)
        self.labelStatusFan4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan4.setText("")
        self.labelStatusFan4.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan4.setScaledContents(True)
        self.labelStatusFan4.setObjectName("labelStatusFan4")
        self.groupBoxCurrentFan5 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan5.setGeometry(QtCore.QRect(10, 270, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan5.setFont(font)
        self.groupBoxCurrentFan5.setObjectName("groupBoxCurrentFan5")
        self.labelStatusFan5 = QtWidgets.QLabel(self.groupBoxCurrentFan5)
        self.labelStatusFan5.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan5.setFont(font)
        self.labelStatusFan5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan5.setText("")
        self.labelStatusFan5.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan5.setScaledContents(True)
        self.labelStatusFan5.setObjectName("labelStatusFan5")
        self.groupBoxCurrentFan6 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan6.setGeometry(QtCore.QRect(10, 330, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan6.setFont(font)
        self.groupBoxCurrentFan6.setObjectName("groupBoxCurrentFan6")
        self.labelStatusFan6 = QtWidgets.QLabel(self.groupBoxCurrentFan6)
        self.labelStatusFan6.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan6.setFont(font)
        self.labelStatusFan6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan6.setText("")
        self.labelStatusFan6.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan6.setScaledContents(True)
        self.labelStatusFan6.setObjectName("labelStatusFan6")
        self.groupBoxCurrentFan9 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan9.setGeometry(QtCore.QRect(90, 150, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan9.setFont(font)
        self.groupBoxCurrentFan9.setObjectName("groupBoxCurrentFan9")
        self.labelStatusFan9 = QtWidgets.QLabel(self.groupBoxCurrentFan9)
        self.labelStatusFan9.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan9.setFont(font)
        self.labelStatusFan9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan9.setText("")
        self.labelStatusFan9.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan9.setScaledContents(True)
        self.labelStatusFan9.setObjectName("labelStatusFan9")
        self.groupBoxCurrentFan8 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan8.setGeometry(QtCore.QRect(90, 90, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan8.setFont(font)
        self.groupBoxCurrentFan8.setObjectName("groupBoxCurrentFan8")
        self.labelStatusFan8 = QtWidgets.QLabel(self.groupBoxCurrentFan8)
        self.labelStatusFan8.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan8.setFont(font)
        self.labelStatusFan8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan8.setText("")
        self.labelStatusFan8.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan8.setScaledContents(True)
        self.labelStatusFan8.setObjectName("labelStatusFan8")
        self.groupBoxCurrentFan11 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan11.setGeometry(QtCore.QRect(90, 270, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan11.setFont(font)
        self.groupBoxCurrentFan11.setObjectName("groupBoxCurrentFan11")
        self.labelStatusFan11 = QtWidgets.QLabel(self.groupBoxCurrentFan11)
        self.labelStatusFan11.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan11.setFont(font)
        self.labelStatusFan11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan11.setText("")
        self.labelStatusFan11.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan11.setScaledContents(True)
        self.labelStatusFan11.setObjectName("labelStatusFan11")
        self.groupBoxCurrentFan7 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan7.setGeometry(QtCore.QRect(90, 30, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan7.setFont(font)
        self.groupBoxCurrentFan7.setObjectName("groupBoxCurrentFan7")
        self.labelStatusFan7 = QtWidgets.QLabel(self.groupBoxCurrentFan7)
        self.labelStatusFan7.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan7.setFont(font)
        self.labelStatusFan7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan7.setText("")
        self.labelStatusFan7.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan7.setScaledContents(True)
        self.labelStatusFan7.setObjectName("labelStatusFan7")
        self.groupBoxCurrentFan12 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan12.setGeometry(QtCore.QRect(90, 330, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan12.setFont(font)
        self.groupBoxCurrentFan12.setObjectName("groupBoxCurrentFan12")
        self.labelStatusFan12 = QtWidgets.QLabel(self.groupBoxCurrentFan12)
        self.labelStatusFan12.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan12.setFont(font)
        self.labelStatusFan12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan12.setText("")
        self.labelStatusFan12.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan12.setScaledContents(True)
        self.labelStatusFan12.setObjectName("labelStatusFan12")
        self.groupBoxCurrentFan10 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan10.setGeometry(QtCore.QRect(90, 210, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan10.setFont(font)
        self.groupBoxCurrentFan10.setObjectName("groupBoxCurrentFan10")
        self.labelStatusFan10 = QtWidgets.QLabel(self.groupBoxCurrentFan10)
        self.labelStatusFan10.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan10.setFont(font)
        self.labelStatusFan10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan10.setText("")
        self.labelStatusFan10.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan10.setScaledContents(True)
        self.labelStatusFan10.setObjectName("labelStatusFan10")
        self.groupBoxCurrentFan15 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan15.setGeometry(QtCore.QRect(10, 450, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan15.setFont(font)
        self.groupBoxCurrentFan15.setObjectName("groupBoxCurrentFan15")
        self.labelStatusFan15 = QtWidgets.QLabel(self.groupBoxCurrentFan15)
        self.labelStatusFan15.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan15.setFont(font)
        self.labelStatusFan15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan15.setText("")
        self.labelStatusFan15.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan15.setScaledContents(True)
        self.labelStatusFan15.setObjectName("labelStatusFan15")
        self.groupBoxCurrentFan14 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan14.setGeometry(QtCore.QRect(90, 390, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan14.setFont(font)
        self.groupBoxCurrentFan14.setObjectName("groupBoxCurrentFan14")
        self.labelStatusFan14 = QtWidgets.QLabel(self.groupBoxCurrentFan14)
        self.labelStatusFan14.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan14.setFont(font)
        self.labelStatusFan14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan14.setText("")
        self.labelStatusFan14.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan14.setScaledContents(True)
        self.labelStatusFan14.setObjectName("labelStatusFan14")
        self.groupBoxCurrentFan13 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan13.setGeometry(QtCore.QRect(10, 390, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan13.setFont(font)
        self.groupBoxCurrentFan13.setObjectName("groupBoxCurrentFan13")
        self.labelStatusFan13 = QtWidgets.QLabel(self.groupBoxCurrentFan13)
        self.labelStatusFan13.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan13.setFont(font)
        self.labelStatusFan13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan13.setText("")
        self.labelStatusFan13.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan13.setScaledContents(True)
        self.labelStatusFan13.setObjectName("labelStatusFan13")
        self.groupBoxCurrentFan16 = QtWidgets.QGroupBox(self.groupBoxWarning)
        self.groupBoxCurrentFan16.setGeometry(QtCore.QRect(90, 450, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxCurrentFan16.setFont(font)
        self.groupBoxCurrentFan16.setObjectName("groupBoxCurrentFan16")
        self.labelStatusFan16 = QtWidgets.QLabel(self.groupBoxCurrentFan16)
        self.labelStatusFan16.setGeometry(QtCore.QRect(10, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelStatusFan16.setFont(font)
        self.labelStatusFan16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStatusFan16.setText("")
        self.labelStatusFan16.setPixmap(QtGui.QPixmap(":/icons/icons/green-led-on.png"))
        self.labelStatusFan16.setScaledContents(True)
        self.labelStatusFan16.setObjectName("labelStatusFan16")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setStyleSheet("background-color: black")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.Layout_right = QtWidgets.QVBoxLayout()
        self.Layout_right.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Layout_right.setContentsMargins(-1, -1, -1, 0)
        self.Layout_right.setObjectName("Layout_right")
        self.Layout_spy = QtWidgets.QVBoxLayout()
        self.Layout_spy.setContentsMargins(-1, -1, -1, 30)
        self.Layout_spy.setObjectName("Layout_spy")
        self.Layout_spy_com = QtWidgets.QHBoxLayout()
        self.Layout_spy_com.setObjectName("Layout_spy_com")
        self.comboBox_moto = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_moto.setObjectName("comboBox_moto")
        self.comboBox_moto.addItem("")
        self.comboBox_moto.addItem("")
        self.comboBox_moto.addItem("")
        self.comboBox_moto.addItem("")
        self.Layout_spy_com.addWidget(self.comboBox_moto)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_spy_com.addItem(spacerItem)
        self.Layout_spy.addLayout(self.Layout_spy_com)
        self.Layout_datapick = QtWidgets.QHBoxLayout()
        self.Layout_datapick.setObjectName("Layout_datapick")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.Layout_datapick.addWidget(self.lineEdit)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.Layout_datapick.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_datapick.addItem(spacerItem1)
        self.Layout_spy.addLayout(self.Layout_datapick)
        self.Layout_spy_button = QtWidgets.QHBoxLayout()
        self.Layout_spy_button.setObjectName("Layout_spy_button")
        self.PB_start = QtWidgets.QPushButton(self.centralwidget)
        self.PB_start.setObjectName("PB_start")
        self.Layout_spy_button.addWidget(self.PB_start)
        self.PB_stop = QtWidgets.QPushButton(self.centralwidget)
        self.PB_stop.setObjectName("PB_stop")
        self.Layout_spy_button.addWidget(self.PB_stop)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_spy_button.addItem(spacerItem2)
        self.Layout_spy.addLayout(self.Layout_spy_button)
        self.Layout_right.addLayout(self.Layout_spy)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("background-color:black;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Layout_right.addWidget(self.line)
        self.label_set = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_set.setFont(font)
        self.label_set.setObjectName("label_set")
        self.Layout_right.addWidget(self.label_set, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 20, -1, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.Layout_right.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_set1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_set1.setObjectName("lineEdit_set1")
        self.horizontalLayout_2.addWidget(self.lineEdit_set1)
        self.lineEdit_set2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_set2.setObjectName("lineEdit_set2")
        self.horizontalLayout_2.addWidget(self.lineEdit_set2)
        self.Layout_right.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 20, -1, 30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.PB_setdata = QtWidgets.QPushButton(self.centralwidget)
        self.PB_setdata.setObjectName("PB_setdata")
        self.horizontalLayout_4.addWidget(self.PB_setdata)
        self.Layout_right.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setStyleSheet("background-color:black;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Layout_right.addWidget(self.line_2)
        self.label_motoctrl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_motoctrl.setFont(font)
        self.label_motoctrl.setObjectName("label_motoctrl")
        self.Layout_right.addWidget(self.label_motoctrl, 0, QtCore.Qt.AlignHCenter)
        self.Layout_set = QtWidgets.QHBoxLayout()
        self.Layout_set.setContentsMargins(-1, 20, -1, 30)
        self.Layout_set.setObjectName("Layout_set")
        self.PB_motostart = QtWidgets.QPushButton(self.centralwidget)
        self.PB_motostart.setObjectName("PB_motostart")
        self.Layout_set.addWidget(self.PB_motostart)
        self.PB_motostop = QtWidgets.QPushButton(self.centralwidget)
        self.PB_motostop.setObjectName("PB_motostop")
        self.Layout_set.addWidget(self.PB_motostop)
        self.Layout_right.addLayout(self.Layout_set)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setStyleSheet("background-color:black;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Layout_right.addWidget(self.line_3)
        self.label_graph = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_graph.setFont(font)
        self.label_graph.setObjectName("label_graph")
        self.Layout_right.addWidget(self.label_graph, 0, QtCore.Qt.AlignHCenter)
        self.Layout_graphcheckbox = QtWidgets.QVBoxLayout()
        self.Layout_graphcheckbox.setContentsMargins(-1, 10, -1, 10)
        self.Layout_graphcheckbox.setObjectName("Layout_graphcheckbox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.Layout_graphcheckbox.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.Layout_graphcheckbox.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.Layout_right.addLayout(self.Layout_graphcheckbox)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.Layout_right.addWidget(self.label_6)
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setObjectName("label_time")
        self.Layout_right.addWidget(self.label_time)
        self.Layout_graph = QtWidgets.QHBoxLayout()
        self.Layout_graph.setContentsMargins(-1, 10, -1, 30)
        self.Layout_graph.setObjectName("Layout_graph")
        self.PB_savefile = QtWidgets.QPushButton(self.centralwidget)
        self.PB_savefile.setObjectName("PB_savefile")
        self.Layout_graph.addWidget(self.PB_savefile)
        self.PB_cleargraph = QtWidgets.QPushButton(self.centralwidget)
        self.PB_cleargraph.setObjectName("PB_cleargraph")
        self.Layout_graph.addWidget(self.PB_cleargraph)
        self.Layout_right.addLayout(self.Layout_graph)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setStyleSheet("background-color:black;")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.Layout_right.addWidget(self.line_6)
        self.horizontalLayout.addLayout(self.Layout_right)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setStyleSheet("background-color: black")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.Layout_graph_2 = QtWidgets.QVBoxLayout()
        self.Layout_graph_2.setObjectName("Layout_graph_2")
        self.horizontalLayout.addLayout(self.Layout_graph_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Monitor"))
        self.PB_reloadfile.setText(_translate("MainWindow", "加载配置文件"))
        self.dataTable.headerItem().setText(0, _translate("MainWindow", "parameter"))
        self.dataTable.headerItem().setText(1, _translate("MainWindow", "value"))
        self.groupBoxWarning.setTitle(_translate("MainWindow", "故障指示灯"))
        self.groupBoxCurrentFan1.setTitle(_translate("MainWindow", "过电流"))
        self.groupBoxCurrentFan2.setTitle(_translate("MainWindow", "过电压"))
        self.groupBoxCurrentFan3.setTitle(_translate("MainWindow", "缺相"))
        self.groupBoxCurrentFan4.setTitle(_translate("MainWindow", "IGBT过热"))
        self.groupBoxCurrentFan5.setTitle(_translate("MainWindow", "过速"))
        self.groupBoxCurrentFan6.setTitle(_translate("MainWindow", "速度波动"))
        self.groupBoxCurrentFan9.setTitle(_translate("MainWindow", "堵转"))
        self.groupBoxCurrentFan8.setTitle(_translate("MainWindow", "欠电压"))
        self.groupBoxCurrentFan11.setTitle(_translate("MainWindow", "过功率"))
        self.groupBoxCurrentFan7.setTitle(_translate("MainWindow", "PFC故障"))
        self.groupBoxCurrentFan12.setTitle(_translate("MainWindow", "启动失败"))
        self.groupBoxCurrentFan10.setTitle(_translate("MainWindow", "芯片过热"))
        self.groupBoxCurrentFan15.setTitle(_translate("MainWindow", "预留3"))
        self.groupBoxCurrentFan14.setTitle(_translate("MainWindow", "预留2"))
        self.groupBoxCurrentFan13.setTitle(_translate("MainWindow", "预留1"))
        self.groupBoxCurrentFan16.setTitle(_translate("MainWindow", "预留4"))
        self.comboBox_moto.setItemText(0, _translate("MainWindow", "MotoA"))
        self.comboBox_moto.setItemText(1, _translate("MainWindow", "MotoB"))
        self.comboBox_moto.setItemText(2, _translate("MainWindow", "MotoC"))
        self.comboBox_moto.setItemText(3, _translate("MainWindow", "MotoD"))
        self.label_5.setText(_translate("MainWindow", "采样间隔ms(默认10ms)"))
        self.PB_start.setText(_translate("MainWindow", "开始监视"))
        self.PB_stop.setText(_translate("MainWindow", "停止监视"))
        self.label_set.setText(_translate("MainWindow", "参数设置"))
        self.label.setText(_translate("MainWindow", "母线电压"))
        self.label_2.setText(_translate("MainWindow", "设定转速"))
        self.PB_setdata.setText(_translate("MainWindow", "发送"))
        self.label_motoctrl.setText(_translate("MainWindow", "电机控制"))
        self.PB_motostart.setText(_translate("MainWindow", "电机启动"))
        self.PB_motostop.setText(_translate("MainWindow", "电机停止"))
        self.label_graph.setText(_translate("MainWindow", "图视窗口"))
        self.label_3.setText(_translate("MainWindow", "勾选左参数面板内容显示图像"))
        self.label_4.setText(_translate("MainWindow", "数据每次重新启动软件会清空请注意保存"))
        self.label_6.setText(_translate("MainWindow", "时间s"))
        self.label_time.setText(_translate("MainWindow", "TextLabel"))
        self.PB_savefile.setText(_translate("MainWindow", "保存文件"))
        self.PB_cleargraph.setText(_translate("MainWindow", "清空数据"))

import MatplotlibShow.recourses_rc
