function T = BPNN_Function(Load_C,Load_T,...
    URX1_C,URX1_T,URY1_C,URY1_T,URZ1_C,URZ1_T,...
    URX2_C,URX2_T,URY2_C,URY2_T,URZ2_C,URZ2_T,...
    URX3_C,URX3_T,URY3_C,URY3_T,URZ3_C,URZ3_T,...
    URX4_C,URX4_T,URY4_C,URY4_T,URZ4_C,URZ4_T,...
    URX5_C,URX5_T,URY5_C,URY5_T,URZ5_C,URZ5_T,...
    URX6_C,URX6_T,URY6_C,URY6_T,URZ6_C,URZ6_T,...
    URX7_C,URX7_T,URY7_C,URY7_T,URZ7_C,URZ7_T,...
    URX8_C,URX8_T,URY8_C,URY8_T,URZ8_C,URZ8_T,...
    URX9_C,URX9_T,URY9_C,URY9_T,URZ9_C,URZ9_T,...
    Frequency_1,Frequency_2,Frequency_3,Frequency_4)
P = [ (URX1_T/Load_T)/(URX1_C/Load_C),(URY1_T/Load_T)/(URY1_C/Load_C),(URZ1_T/Load_T)/(URZ1_C/Load_C), ...
      (URX2_T/Load_T)/(URX2_C/Load_C),(URY2_T/Load_T)/(URY2_C/Load_C),(URZ2_T/Load_T)/(URZ2_C/Load_C), ...
      (URX3_T/Load_T)/(URX3_C/Load_C),(URY3_T/Load_T)/(URY3_C/Load_C),(URZ3_T/Load_T)/(URZ3_C/Load_C), ...
      (URX4_T/Load_T)/(URX4_C/Load_C),(URY4_T/Load_T)/(URY4_C/Load_C),(URZ4_T/Load_T)/(URZ4_C/Load_C), ...
      (URX5_T/Load_T)/(URX5_C/Load_C),(URY5_T/Load_T)/(URY5_C/Load_C),(URZ5_T/Load_T)/(URZ5_C/Load_C), ...
      (URX6_T/Load_T)/(URX6_C/Load_C),(URY6_T/Load_T)/(URY6_C/Load_C),(URZ6_T/Load_T)/(URZ6_C/Load_C), ...
      (URX7_T/Load_T)/(URX7_C/Load_C),(URY7_T/Load_T)/(URY7_C/Load_C),(URZ7_T/Load_T)/(URZ7_C/Load_C), ...
      (URX8_T/Load_T)/(URX8_C/Load_C),(URY8_T/Load_T)/(URY8_C/Load_C),(URZ8_T/Load_T)/(URZ8_C/Load_C), ...
      (URX9_T/Load_T)/(URX9_C/Load_C),(URY9_T/Load_T)/(URY9_C/Load_C),(URZ9_T/Load_T)/(URZ9_C/Load_C), ...
      Frequency_1, Frequency_2, Frequency_3, Frequency_4]';
  
load('BPnet2');

T = sim(net,P);
T = round(T)