# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowTest.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(1219, 680)
        MainWindow2.setMinimumSize(QtCore.QSize(1219, 680))
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton1_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton1_5.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton1_5.setStyleSheet("background-color: rgb(240,240,240);border:none;\n"
"font: 25pt \"Agency FB\";")
        self.pushButton1_5.setCheckable(False)
        self.pushButton1_5.setAutoDefault(False)
        self.pushButton1_5.setObjectName("pushButton1_5")
        self.verticalLayout_4.addWidget(self.pushButton1_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton1_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton1_4.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton1_4.setAutoDefault(False)
        self.pushButton1_4.setObjectName("pushButton1_4")
        self.horizontalLayout_9.addWidget(self.pushButton1_4)
        self.pushButton2_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton2_4.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton2_4.setObjectName("pushButton2_4")
        self.horizontalLayout_9.addWidget(self.pushButton2_4)
        self.pushButton3_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton3_4.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton3_4.setObjectName("pushButton3_4")
        self.horizontalLayout_9.addWidget(self.pushButton3_4)
        self.pushButton4_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton4_4.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton4_4.setObjectName("pushButton4_4")
        self.horizontalLayout_9.addWidget(self.pushButton4_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton1_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton1_3.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton1_3.setAutoDefault(False)
        self.pushButton1_3.setObjectName("pushButton1_3")
        self.horizontalLayout_8.addWidget(self.pushButton1_3)
        self.pushButton2_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton2_3.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton2_3.setObjectName("pushButton2_3")
        self.horizontalLayout_8.addWidget(self.pushButton2_3)
        self.pushButton3_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton3_3.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton3_3.setObjectName("pushButton3_3")
        self.horizontalLayout_8.addWidget(self.pushButton3_3)
        self.pushButton4_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton4_3.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton4_3.setObjectName("pushButton4_3")
        self.horizontalLayout_8.addWidget(self.pushButton4_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton1_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton1_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton1_2.setAutoDefault(False)
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.horizontalLayout_7.addWidget(self.pushButton1_2)
        self.pushButton2_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton2_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton2_2.setObjectName("pushButton2_2")
        self.horizontalLayout_7.addWidget(self.pushButton2_2)
        self.pushButton3_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton3_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton3_2.setObjectName("pushButton3_2")
        self.horizontalLayout_7.addWidget(self.pushButton3_2)
        self.pushButton4_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton4_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton4_2.setObjectName("pushButton4_2")
        self.horizontalLayout_7.addWidget(self.pushButton4_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton5_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton5_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton5_2.setObjectName("pushButton5_2")
        self.horizontalLayout_14.addWidget(self.pushButton5_2)
        self.pushButton6_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton6_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton6_2.setObjectName("pushButton6_2")
        self.horizontalLayout_14.addWidget(self.pushButton6_2)
        self.pushButton7_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton7_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton7_2.setObjectName("pushButton7_2")
        self.horizontalLayout_14.addWidget(self.pushButton7_2)
        self.pushButton8_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton8_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton8_2.setObjectName("pushButton8_2")
        self.horizontalLayout_14.addWidget(self.pushButton8_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setChecked(True)
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_2.addWidget(self.timeEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setMinimumSize(QtCore.QSize(403, 383))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 404, 505))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton1.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton1.setAutoDefault(False)
        self.pushButton1.setObjectName("pushButton1")
        self.horizontalLayout_6.addWidget(self.pushButton1)
        self.pushButton2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton2.setObjectName("pushButton2")
        self.horizontalLayout_6.addWidget(self.pushButton2)
        self.pushButton3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton3.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton3.setObjectName("pushButton3")
        self.horizontalLayout_6.addWidget(self.pushButton3)
        self.pushButton4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton4.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton4.setObjectName("pushButton4")
        self.horizontalLayout_6.addWidget(self.pushButton4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton5.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton5.setObjectName("pushButton5")
        self.horizontalLayout_13.addWidget(self.pushButton5)
        self.pushButton6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton6.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton6.setObjectName("pushButton6")
        self.horizontalLayout_13.addWidget(self.pushButton6)
        self.pushButton7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton7.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton7.setObjectName("pushButton7")
        self.horizontalLayout_13.addWidget(self.pushButton7)
        self.pushButton8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton8.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton8.setObjectName("pushButton8")
        self.horizontalLayout_13.addWidget(self.pushButton8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton9.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton9.setObjectName("pushButton9")
        self.horizontalLayout_10.addWidget(self.pushButton9)
        self.pushButton10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton10.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton10.setObjectName("pushButton10")
        self.horizontalLayout_10.addWidget(self.pushButton10)
        self.pushButton11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton11.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton11.setObjectName("pushButton11")
        self.horizontalLayout_10.addWidget(self.pushButton11)
        self.pushButton12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton12.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton12.setObjectName("pushButton12")
        self.horizontalLayout_10.addWidget(self.pushButton12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton13.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton13.setObjectName("pushButton13")
        self.horizontalLayout_12.addWidget(self.pushButton13)
        self.pushButton14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton14.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton14.setObjectName("pushButton14")
        self.horizontalLayout_12.addWidget(self.pushButton14)
        self.pushButton15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton15.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton15.setObjectName("pushButton15")
        self.horizontalLayout_12.addWidget(self.pushButton15)
        self.pushButton16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton16.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton16.setObjectName("pushButton16")
        self.horizontalLayout_12.addWidget(self.pushButton16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 400))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView.setMinimumSize(QtCore.QSize(300, 200))
        self.graphicsView.setMaximumSize(QtCore.QSize(400, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_5.addWidget(self.graphicsView)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1219, 26))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "主界面"))
        self.groupBox_3.setTitle(_translate("MainWindow2", "软件信息"))
        self.pushButton1_5.setText(_translate("MainWindow2", "玻璃状态监测系统"))
        self.pushButton1_4.setText(_translate("MainWindow2", "区域1"))
        self.pushButton2_4.setText(_translate("MainWindow2", "区域2"))
        self.pushButton3_4.setText(_translate("MainWindow2", "区域3"))
        self.pushButton4_4.setText(_translate("MainWindow2", "区域4"))
        self.pushButton1_3.setText(_translate("MainWindow2", "区域5"))
        self.pushButton2_3.setText(_translate("MainWindow2", "区域6"))
        self.pushButton3_3.setText(_translate("MainWindow2", "区域7"))
        self.pushButton4_3.setText(_translate("MainWindow2", "区域8"))
        self.pushButton1_2.setText(_translate("MainWindow2", "区域9"))
        self.pushButton2_2.setText(_translate("MainWindow2", "区域10"))
        self.pushButton3_2.setText(_translate("MainWindow2", "区域11"))
        self.pushButton4_2.setText(_translate("MainWindow2", "区域12"))
        self.pushButton5_2.setText(_translate("MainWindow2", "区域13"))
        self.pushButton6_2.setText(_translate("MainWindow2", "区域14"))
        self.pushButton7_2.setText(_translate("MainWindow2", "区域15"))
        self.pushButton8_2.setText(_translate("MainWindow2", "区域16"))
        self.groupBox.setTitle(_translate("MainWindow2", "玻璃状态展示"))
        self.radioButton_2.setText(_translate("MainWindow2", "历史记录"))
        self.radioButton.setText(_translate("MainWindow2", "实时监测"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow2", "yyyy/M/d/HH/mm"))
        self.pushButton1.setText(_translate("MainWindow2", "玻璃1"))
        self.pushButton2.setText(_translate("MainWindow2", "玻璃2"))
        self.pushButton3.setText(_translate("MainWindow2", "玻璃3"))
        self.pushButton4.setText(_translate("MainWindow2", "玻璃4"))
        self.pushButton5.setText(_translate("MainWindow2", "玻璃5"))
        self.pushButton6.setText(_translate("MainWindow2", "玻璃6"))
        self.pushButton7.setText(_translate("MainWindow2", "玻璃7"))
        self.pushButton8.setText(_translate("MainWindow2", "玻璃8"))
        self.pushButton9.setText(_translate("MainWindow2", "玻璃9"))
        self.pushButton10.setText(_translate("MainWindow2", "玻璃10"))
        self.pushButton11.setText(_translate("MainWindow2", "玻璃11"))
        self.pushButton12.setText(_translate("MainWindow2", "玻璃12"))
        self.pushButton13.setText(_translate("MainWindow2", "玻璃13"))
        self.pushButton14.setText(_translate("MainWindow2", "玻璃14"))
        self.pushButton15.setText(_translate("MainWindow2", "玻璃15"))
        self.pushButton16.setText(_translate("MainWindow2", "玻璃16"))
        self.groupBox_2.setTitle(_translate("MainWindow2", "状态统计图"))

